enum ActionTypes {
    RESET_PASSWORD = "RESET_PASSWORD",
    RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR",
    RESET_PASSWORD_CLEAR = "RESET_PASSWORD_CLEAR",
}

export default ActionTypes
