enum ActionTypes {
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR",
    FORGOT_PASSWORD_CLEAR = "FORGOT_PASSWORD_CLEAR",
}

export default ActionTypes

